# Generated by Django 4.0.2 on 2022-03-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_likes_author_url_alter_likes_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='author_url',
            field=models.TextField(max_length=250),
        ),
    ]
