# Generated by Django 4.0.2 on 2022-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_likes_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='summary',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
