# Generated by Django 3.2.8 on 2021-10-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('MD', 'text/markdown'), ('PL', 'text/plain'), ('B64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PL', max_length=4)),
                ('content_text', models.TextField()),
                ('content_media', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('page_size', models.PositiveSmallIntegerField(default=0)),
                ('first_comments_page', models.URLField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('PB', 'PUBLIC'), ('FRD', 'FRIENDS')], max_length=10)),
                ('unlisted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PL', 'text/plain'), ('MD', 'text/markdown')], max_length=2)),
                ('comment', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post')),
            ],
        ),
    ]
