# Generated by Django 3.2.8 on 2021-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImageUrl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
