# Generated by Django 3.2.8 on 2021-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='githubUrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
