# Generated by Django 3.1.6 on 2021-11-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentAuthor',
            new_name='commentAuthorID',
        ),
    ]
