# Generated by Django 2.1.5 on 2019-02-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.AuthorProfile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='authorA',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='follow',
            name='authorB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.AuthorProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(to='api.AuthorProfile'),
        ),
    ]
