# Generated by Django 2.1.5 on 2019-03-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190217_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
