# Generated by Django 3.1.6 on 2021-11-03 22:04

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211103_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='displayName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorID',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
