# Generated by Django 2.1.5 on 2019-02-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190217_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, to='api.AuthorProfile'),
        ),
    ]
