# Generated by Django 2.1.5 on 2019-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190220_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
