# Generated by Django 3.1.6 on 2021-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211104_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postURL',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='post title', max_length=150),
        ),
    ]
