# Generated by Django 2.1.5 on 2019-03-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190324_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='host',
            field=models.URLField(default='http://127.0.0.1:1234/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveruser',
            name='password',
            field=models.CharField(default='server2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveruser',
            name='username',
            field=models.CharField(default='server2', max_length=100),
            preserve_default=False,
        ),
    ]
