# Generated by Django 2.1.5 on 2019-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190324_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
