# Generated by Django 4.1.6 on 2023-02-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('post_id', models.URLField(max_length=100)),
                ('post_source', models.URLField(max_length=100)),
                ('post_origin', models.URLField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
                ('comment_count', models.IntegerField()),
                ('comments', models.URLField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('is_unlisted', models.BooleanField()),
            ],
        ),
    ]
