# Generated by Django 2.1.5 on 2019-03-12 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('preferences_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='preferences.Preferences')),
                ('serve_others_images', models.BooleanField(default=True)),
                ('serve_others_posts', models.BooleanField(default=True)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
