# Generated by Django 4.0.2 on 2022-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgContent',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
