# Generated by Django 2.1.5 on 2019-02-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190221_2248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_post', 'category')},
        ),
    ]
