# Generated by Django 4.1.6 on 2023-03-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
        ('posts', '0002_post_origin_post_source'),
    ]

    operations = [
    ]
