# Generated by Django 2.1.7 on 2019-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_auto_20190312_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(
                choices=[('text/plain', 'Plain'), ('text/markdown', 'Markdown'), ('application/base64', 'Base64'),
                         ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], default='text/plain',
                max_length=18),
        ),
    ]
