# Generated by Django 4.1.7 on 2023-03-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_origin_post_source'),
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
    ]
