# Generated by Django 4.0.2 on 2022-03-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
        ('posts', '0003_post_imgcontent'),
    ]

    operations = [
    ]
