# Generated by Django 4.0.2 on 2022-03-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_0002_comment_0003_post_imgcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AlterField(
            model_name='post',
            name='imgContent',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
