# Generated by Django 2.1.5 on 2019-02-27 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20190226_2351'),
        ('posts', '0004_auto_20190226_1851'),
    ]

    operations = [
    ]
