# Generated by Django 4.1.6 on 2023-03-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20230309_0328'),
        ('posts', '0004_merge_20230311_1342'),
    ]

    operations = [
    ]
