# Generated by Django 2.1.5 on 2019-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_merge_20190227_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
