# Generated by Django 4.0.2 on 2022-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
        ('posts', '0005_delete_postimage_alter_post_imgcontent'),
    ]

    operations = [
    ]
