# Generated by Django 4.0.2 on 2022-03-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgContent',
            new_name='img_content',
        ),
    ]
