# Generated by Django 2.1.5 on 2019-03-03 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_auto_20190227_1943'),
        ('posts', '0006_auto_20190227_1951'),
    ]

    operations = [
    ]
