# Generated by Django 2.1.5 on 2019-03-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20190303_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FOAF', 'Friend of a Friend'), ('FRIENDS', 'Friends'), ('SERVERONLY', 'Server Only')], default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=200),
        ),
    ]
