# Generated by Django 4.0.2 on 2022-03-24 02:17

from django.db import migrations, models
import socialdistribution.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_imgcontent_post_img_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_content',
            field=models.ImageField(blank=True, null=True, storage=socialdistribution.storage.ImageStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
