# Generated by Django 2.1.5 on 2019-03-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190314_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visible_posts', to='posts.ExternalUser'),
        ),
    ]
