# Generated by Django 3.2.8 on 2021-10-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_add_comment_url_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.URLField(default='http://127.0.0.1:8000/author/9de17f29c12e8f97bcbbd34cc908f1baba40658e/posts/764efa883dda1e11db47671c4a3bbd9e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='summary',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('author', 'object'), name='unique_like'),
        ),
    ]
