# Generated by Django 2.1.5 on 2019-03-10 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0008_auto_20190303_1811'),
        ('posts', '0002_user_approved'),
    ]

    operations = [
    ]
