# Generated by Django 2.1.7 on 2019-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0008_auto_20190314_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='githubEtag',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='githubLastId',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
