# Generated by Django 4.1.7 on 2023-03-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='commentsSrc',
        ),
    ]
