# Generated by Django 2.1.7 on 2019-03-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0008_auto_20190314_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibleTo',
        ),
        migrations.AddField(
            model_name='viewer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_posts',
                                    to='posts.Post'),
        ),
    ]
