# Generated by Django 4.0.2 on 2022-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like_context_like_object_like_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='context',
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=4),
        ),
    ]
