# Generated by Django 2.1.7 on 2019-03-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190324_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='githubEtag',
        ),
    ]
