# Generated by Django 2.1.5 on 2019-03-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow_followrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('requester', 'requestee')},
        ),
    ]
