# Generated by Django 4.0.2 on 2022-03-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_like_context_like_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='object',
        ),
        migrations.RemoveField(
            model_name='like',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='like',
            name='type',
        ),
    ]
