# Generated by Django 2.1.7 on 2019-03-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0009_auto_20190322_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalUser',
        ),
        migrations.AlterField(
            model_name='viewer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibleTo',
                                    to='posts.Post'),
        ),
    ]
