# Generated by Django 2.1.7 on 2019-03-25 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0010_auto_20190322_1855'),
        ('posts', '0010_remove_user_githubetag'),
    ]

    operations = [
    ]
