# Generated by Django 2.1.5 on 2019-03-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_merge_20190310_1700'),
        ('posts', '0010_auto_20190310_1427'),
    ]

    operations = [
    ]
