# Generated by Django 4.0.2 on 2022-03-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_img_content'),
        ('posts', '0010_remove_like_object_remove_like_summary_and_more'),
    ]

    operations = [
    ]
