# Generated by Django 2.1.7 on 2019-03-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_20190324_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='WWUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('local', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='posts.WWUser', to_field='url'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee',
                                    to='posts.WWUser', to_field='url'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower',
                                    to='posts.WWUser', to_field='url'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='requestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee',
                                    to='posts.WWUser', to_field='url'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester',
                                    to='posts.WWUser', to_field='url'),
        ),
    ]
