# Generated by Django 2.1.7 on 2019-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0012_auto_20190328_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwuser',
            name='user_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
