# Generated by Django 2.1.7 on 2019-03-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0013_auto_20190328_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
    ]
