# Generated by Django 2.1.7 on 2019-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0014_auto_20190330_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwuser',
            name='user_id',
            field=models.CharField(max_length=1024, null=True, unique=True),
        ),
    ]
