# Generated by Django 2.1.7 on 2019-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0015_auto_20190401_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='api',
            field=models.URLField(default=''),
        ),
    ]
