# Generated by Django 2.1.7 on 2019-04-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0016_server_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='trailing_slash',
            field=models.BooleanField(default=True),
        ),
    ]
