# Generated by Django 4.0.2 on 2022-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_request_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
