# Generated by Django 4.1.6 on 2023-03-03 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_authormodel_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('type', models.CharField(default='post', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(default='', max_length=100)),
                ('origin', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('contentType', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=100)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, size=None)),
                ('count', models.IntegerField(default=1023)),
                ('comments', models.CharField(default='', max_length=100)),
                ('commentsSrc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, size=None)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.BooleanField(default=True)),
                ('unlisted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['type', 'title', 'id', 'source', 'origin', 'description', 'contentType', 'content', 'author', 'categories', 'count', 'comments', 'commentsSrc', 'published', 'visibility', 'unlisted'],
            },
        ),
    ]
