# Generated by Django 4.1.7 on 2023-03-03 22:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_authormodel_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
