# Generated by Django 3.2.8 on 2021-10-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('visibility', models.CharField(blank=True, max_length=200, verbose_name='visibility')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
