# Generated by Django 3.2.9 on 2021-11-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211121_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.TextField(default='http://localhost:8000', verbose_name='host'),
            preserve_default=False,
        ),
    ]
