# Generated by Django 4.0.2 on 2022-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='credentials',
        ),
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(default='bruh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='bruh', max_length=100),
            preserve_default=False,
        ),
    ]
