# Generated by Django 4.0.2 on 2022-03-23 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0002_alter_node_remote_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_credentials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
