# Generated by Django 4.0.2 on 2022-03-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_node_remote_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='outbound_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='outbound_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
