# Generated by Django 4.1.6 on 2023-03-01 07:33

import apps.authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('displayName', models.CharField(blank=True, max_length=200)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('profileImage', models.ImageField(blank=True, upload_to='')),
                ('friend_list', models.JSONField(blank=True, default=apps.authors.models.Author.friendlist_template)),
            ],
        ),
    ]
