# Generated by Django 4.1.6 on 2023-03-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
