# Generated by Django 3.1.6 on 2023-02-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('profileImage', models.URLField()),
                ('url', models.URLField(editable=False)),
                ('host', models.URLField(editable=False)),
                ('friends', models.ManyToManyField(related_name='_author_friends_+', to='author.Author')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
