# Generated by Django 4.1.7 on 2023-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
