# Generated by Django 4.1.6 on 2023-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20230212_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(to='author.author'),
        ),
    ]
