# Generated by Django 4.1.7 on 2023-03-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_inbox_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['displayName']},
        ),
    ]
