# Generated by Django 3.1.6 on 2023-02-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('author', '0002_auto_20230212_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='author.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='author.author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=models.Index(fields=['content_type', 'object_id'], name='author_inbo_content_f0dd76_idx'),
        ),
    ]
