# Generated by Django 3.1.6 on 2023-02-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20230225_0737'),
        ('author', '0003_alter_author_friends_alter_author_profileimage'),
    ]

    operations = [
    ]
