# Generated by Django 3.1.6 on 2023-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_merge_20230227_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='author.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
