# Generated by Django 4.1.7 on 2023-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_auto_20230227_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, to='author.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
