# Generated by Django 3.1.6 on 2023-02-28 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_auto_20230227_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
