# Generated by Django 4.1.7 on 2023-03-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_alter_author_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='type',
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='Summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
