# Generated by Django 3.1.6 on 2023-02-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_auto_20230227_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
    ]
