# Generated by Django 4.1.7 on 2023-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0011_auto_20230228_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, to='author.author'),
        ),
    ]
