# Generated by Django 4.1.7 on 2023-03-03 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_alter_author_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.UUID('581a0543-23b3-4813-84ea-bf9a39bd9607'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
