# Generated by Django 4.1.6 on 2023-03-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_friends_alter_author_profileimage'),
        ('author', '0012_alter_author_friends'),
    ]

    operations = [
    ]
