# Generated by Django 4.1.6 on 2023-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_merge_20230302_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
