# Generated by Django 4.0.2 on 2022-03-13 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Follow', 'Follow Request'), ('Like', 'Like')], max_length=100)),
                ('actor', models.URLField(max_length=350)),
                ('summary', models.CharField(max_length=250)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
