version: "3.3"

services:
  react:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    # avoid node_modules being overwritten
    volumes:
      - '.:/app/frontend'
      - '/app/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

