# Generated by Django 3.2.8 on 2021-10-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='type',
            new_name='item_type',
        ),
    ]
