# Generated by Django 3.0.3 on 2020-02-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.URLField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted')], default='U', max_length=1)),
            ],
        ),
    ]
