# Generated by Django 3.1.6 on 2021-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.URLField(default='Null'),
            preserve_default=False,
        ),
    ]
