# Generated by Django 3.1.6 on 2021-10-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='context',
            field=models.URLField(blank=True, null=True),
        ),
    ]
