# Generated by Django 3.2.8 on 2021-10-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211024_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(max_length=32),
        ),
    ]
