# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FOAF', 'FOAF'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private'), ('SERVERONLY', 'This Server Only')], default='PUBLIC', max_length=10),
        ),
    ]
