# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170311_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='use_markdown',
            field=models.BooleanField(default=False),
        ),
    ]
