# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_merge_20170311_1748'),
        ('post', '0005_post_use_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(related_name='visible_posts', to='dashboard.Author'),
        ),
    ]
