# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


def set_post_html_defaults(apps, schema_editor):
    Post = apps.get_model('post', 'Post')
    for post in Post.objects.all().iterator():
        post.post_story_html = post.post_story
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0006_post_visibleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_story_html',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.RunPython(set_post_html_defaults),
        migrations.AlterField(
            model_name='post',
            name='post_story_html',
            field=models.TextField(),
        ),
    ]
