# Generated by Django 4.1.6 on 2023-02-11 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_host', models.URLField()),
                ('display_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(max_length=100)),
                ('author_github', models.URLField(max_length=100)),
                ('profile_image', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
