# Generated by Django 3.2.7 on 2021-09-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='displayName',
            new_name='display_name',
        ),
    ]
