# Generated by Django 3.2.7 on 2021-09-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_displayname_author_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorFriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='authors.author')),
                ('author_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='authors.author')),
            ],
        ),
    ]
