# Generated by Django 3.2.7 on 2021-09-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_authorfriendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorFollowingRelation',
        ),
    ]
