# Generated by Django 3.2.7 on 2021-09-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_delete_authorfollowingrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False),
        ),
    ]
