# Generated by Django 3.2.7 on 2021-09-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_author_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
