# Generated by Django 3.2.7 on 2021-10-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_create_following_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.JSONField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_objects', to='authors.author')),
            ],
        ),
    ]
