# Generated by Django 3.2.7 on 2021-10-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_inboxobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxobject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_objects', to='authors.author'),
        ),
    ]
