# Generated by Django 3.2.7 on 2021-10-17 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_inboxobject_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=80, primary_key=True, serialize=False),
        ),
    ]
