# Generated by Django 3.2.7 on 2021-10-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authors', '0015_auto_20211017_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxobject',
            name='object',
        ),
        migrations.AddField(
            model_name='inboxobject',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inboxobject',
            name='object_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
