# Generated by Django 4.1.7 on 2023-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authormodel", name="host", field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="authormodel", name="url", field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="commentsmodel", name="host", field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="followmodel",
            name="follower",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="followmodel",
            name="following",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="likemodel", name="summary", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="postsmodel",
            name="origin",
            field=models.URLField(default="http://localhost:8000"),
        ),
        migrations.AlterField(
            model_name="postsmodel", name="source", field=models.URLField(default=""),
        ),
    ]
