# Generated by Django 4.1.7 on 2023-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_inboxmodel_comment_remove_inboxmodel_follow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authormodel", name="github", field=models.URLField(default=""),
        ),
    ]
