# Generated by Django 4.1.7 on 2023-03-24 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_authormodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="id",
            field=models.URLField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="followmodel",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="inboxmodel",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="likemodel",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="likemodel",
            name="object",
            field=models.URLField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="postsmodel",
            name="id",
            field=models.URLField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="postsmodel",
            name="origin",
            field=models.URLField(default="http://localhost:8000/services"),
        ),
    ]
