# Generated by Django 4.1.7 on 2023-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_commentsmodel_id_alter_followmodel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsmodel",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=100,
            ),
        ),
    ]
