# Generated by Django 4.1.7 on 2023-03-27 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_imagemodel_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='origin',
            field=models.URLField(default='http://localhost:8000'),
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_url', models.URLField()),
                ('node_name', models.CharField(default='anonymous node', max_length=25)),
                ('t16_uname', models.CharField(max_length=25)),
                ('t16_pw', models.CharField(max_length=25)),
                ('node_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('node_url',),
            },
        ),
    ]
