# Generated by Django 4.1.6 on 2023-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
