# Generated by Django 4.0.2 on 2022-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_verified_alter_author_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
    ]
