# Generated by Django 3.1.7 on 2021-03-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_remove_likepost_at_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='at_context',
        ),
    ]
