# Generated by Django 3.1.7 on 2021-03-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0004_remove_likecomment_at_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='at_context',
            field=models.URLField(default='https://www.w3.org/ns/activitystreams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likepost',
            name='at_context',
            field=models.URLField(default='https://www.w3.org/ns/activitystreams'),
            preserve_default=False,
        ),
    ]
