# Generated by Django 3.2.9 on 2021-12-06 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment')], max_length=10)),
                ('item', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
    ]
