# Generated by Django 3.2.9 on 2021-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='item',
            field=models.TextField(),
        ),
    ]
