# Generated by Django 3.2.9 on 2021-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_inboxitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='item_type',
            field=models.CharField(choices=[('post', 'Post'), ('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment')], max_length=10),
        ),
    ]
