# Generated by Django 4.1.7 on 2023-03-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_authormodel_github"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.authormodel",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="likemodel",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.authormodel",
                to_field="id",
            ),
        ),
    ]
