# Generated by Django 4.1.6 on 2023-03-03 10:02

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_postsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('type', models.CharField(default='comment', max_length=100)),
                ('author', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(default=builtins.id, max_length=100)),
                ('host', models.CharField(default='', max_length=100)),
                ('contentType', models.CharField(default='', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default='', max_length=500)),
                ('post_id', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['type', 'author', 'comment', 'host', 'contentType', 'published', 'id', 'post_id'],
            },
        ),
    ]
