# Generated by Django 4.1.6 on 2023-03-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_commentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('type', models.CharField(default='like', max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['summary', 'type', 'author', 'object'],
            },
        ),
    ]
