# Generated by Django 4.1.7 on 2023-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_postsmodel_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("friends", "Friends"),
                    ("true_friends", "True Friends"),
                    ("not_friends", "Not Friends"),
                ],
                default="not_friends",
                max_length=100,
            ),
        ),
    ]
