# Generated by Django 4.1.7 on 2023-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_commentsmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='profileImage',
            field=models.TextField(default=''),
        ),
    ]
