# Generated by Django 4.1.7 on 2023-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_followmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("friends", "Friends"),
                    ("not_friends", "Not Friends"),
                ],
                default="not_friends",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="likemodel", name="object", field=models.URLField(default=""),
        ),
    ]
