# Generated by Django 4.1.7 on 2023-03-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_followmodel_status_alter_likemodel_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='origin',
            field=models.URLField(default='http://localhost:8000'),
        ),
    ]
