# Generated by Django 4.1.7 on 2023-03-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_postsmodel_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='origin',
            field=models.URLField(default='http://localhost:8000/service'),
        ),
    ]
