# Generated by Django 4.1.7 on 2023-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_image_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='url_id',
            field=models.URLField(default=''),
        ),
    ]
