# Generated by Django 4.1.7 on 2023-03-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_postsmodel_origin_nodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='origin',
            field=models.URLField(default='http://localhost:8000/service/author/posts'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='source',
            field=models.URLField(default='http://localhost:8000/service/author/posts'),
        ),
    ]
