# Generated by Django 3.2.7 on 2021-10-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='author',
            name='host',
        ),
    ]
