# Generated by Django 3.2.7 on 2021-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211024_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
