# Generated by Django 3.2.7 on 2021-10-26 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(default='post', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('contentType', models.CharField(default='text/plain', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.author')),
            ],
        ),
    ]
