# Generated by Django 3.2.7 on 2021-10-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211024_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='<django.db.models.fields.URLField>/author/<django.db.models.fields.UUIDField>', null=True),
        ),
    ]
