# Generated by Django 3.2.7 on 2021-10-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
