# Generated by Django 3.2.7 on 2021-10-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='<django.db.models.fields.CharField>/author/<django.db.models.fields.UUIDField>', max_length=200, null=True),
        ),
    ]
