# Generated by Django 3.2.7 on 2021-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y-%m-%d/'),
        ),
    ]
