# Generated by Django 3.2.7 on 2021-10-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211024_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
    ]
