# Generated by Django 3.2.7 on 2021-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211026_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
