# Generated by Django 3.2.7 on 2021-10-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
