# Generated by Django 3.2.7 on 2021-10-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
