# Generated by Django 4.1.6 on 2023-02-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('comment_content', models.TextField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('comment_id', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('size', models.IntegerField()),
                ('post', models.URLField(max_length=100)),
                ('comment_id', models.URLField(max_length=100)),
            ],
        ),
    ]
