# Generated by Django 3.1.6 on 2021-02-20 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('model_type', models.CharField(default='comment', max_length=10)),
                ('comment', models.TextField()),
                ('ContentType', models.CharField(default='text/plain', max_length=20)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('commentID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('authorID', models.CharField(max_length=40)),
                ('postID', models.UUIDField()),
            ],
        ),
    ]
