# Generated by Django 3.1.6 on 2021-02-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikePost',
        ),
    ]
