# Generated by Django 3.1.6 on 2021-02-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='model_type',
        ),
    ]
