# Generated by Django 3.1.6 on 2021-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorID',
            field=models.CharField(max_length=40),
        ),
    ]
