# Generated by Django 3.1.6 on 2021-02-24 03:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_auto_20210224_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('at_context', models.URLField()),
                ('summary', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('likeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author_like_ID', models.CharField(max_length=40)),
                ('author_write_comment_ID', models.CharField(max_length=40)),
                ('author_write_article_ID', models.CharField(max_length=40)),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.comment')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.post')),
            ],
        ),
    ]
