# Generated by Django 3.1.6 on 2021-02-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_likepost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='type',
            field=models.CharField(default='like', max_length=100),
            preserve_default=False,
        ),
    ]
