# Generated by Django 3.1.6 on 2021-02-23 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_auto_20210222_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('at_context', models.URLField()),
                ('summary', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('likeID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author_like_ID', models.CharField(max_length=40)),
                ('author_write_article_ID', models.CharField(max_length=40)),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
