# Generated by Django 3.1.6 on 2021-02-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
