# Generated by Django 3.1.6 on 2021-02-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_likecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='author_write_comment_ID',
        ),
    ]
