# Generated by Django 3.2.8 on 2021-10-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(editable=False)),
                ('url', models.URLField(editable=False)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='follower', to='backend.Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(editable=False, max_length=500)),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=30)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_liked', to='backend.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.comment')),
            ],
            options={
                'unique_together': {('author', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='backend.author')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='backend.author')),
            ],
            options={
                'unique_together': {('requestor', 'requestee')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(editable=False, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField(blank=True, max_length=500)),
                ('origin', models.URLField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FOLLOWERS', 'FOLLOWERS'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=30)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='backend.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_liked', to='backend.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.post')),
            ],
            options={
                'unique_together': {('author', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.URLField(editable=False, max_length=500)),
                ('type', models.CharField(default='Like', max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.post'),
        ),
        migrations.CreateModel(
            name='InboxPostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes_in_inbox', to='backend.author')),
                ('post_like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.postlike')),
            ],
            options={
                'unique_together': {('author', 'post_like')},
            },
        ),
        migrations.CreateModel(
            name='InboxPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_in_inbox', to='backend.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.post')),
            ],
            options={
                'unique_together': {('author', 'post')},
            },
        ),
        migrations.CreateModel(
            name='InboxFriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_in_inbox', to='backend.author')),
                ('friend_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.friendrequest')),
            ],
            options={
                'unique_together': {('author', 'friend_request')},
            },
        ),
        migrations.CreateModel(
            name='InboxCommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes_in_inbox', to='backend.author')),
                ('comment_like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.commentlike')),
            ],
            options={
                'unique_together': {('author', 'comment_like')},
            },
        ),
        migrations.CreateModel(
            name='InboxComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_in_inbox', to='backend.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.comment')),
            ],
            options={
                'unique_together': {('author', 'comment')},
            },
        ),
    ]
