# Generated by Django 3.2.8 on 2021-10-15 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default='d28e292511cb458b98cda5f40628f0fc', editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField()),
                ('url', models.URLField()),
                ('displayName', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('followers', models.ManyToManyField(blank=True, related_name='follower', to='backend.Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default='510d854e70cc47e988e981e799f45f5a', editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=240)),
                ('contentType', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], max_length=30)),
                ('content', models.TextField(max_length=2000)),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FOLLOWERS', 'FOLLOWERS'), ('PRIVATE', 'PRIVATE')], max_length=30)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='backend.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default='11bfa62dd9fd4fd5bf21c83a90ccd65d', editable=False, primary_key=True, serialize=False, unique=True)),
                ('contentType', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=30)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
            ],
            options={
                'unique_together': {('author', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.comment')),
            ],
            options={
                'unique_together': {('author', 'comment')},
            },
        ),
    ]
