# Generated by Django 3.1.6 on 2021-03-09 22:07

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('friends', models.BooleanField(default=False)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='backend.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='backend.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_author_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_conetnt',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='backend.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_content',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='backend.author'),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='backend.follow')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='backend.like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='backend.post')),
            ],
        ),
    ]
