# Generated by Django 3.2.8 on 2021-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_backend_author_followers_+', to='backend.Author'),
        ),
    ]
