# Generated by Django 3.2.8 on 2021-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='requesting_auth_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
