# Generated by Django 3.2.8 on 2021-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='2c958667148e4d1aba1614fb4705b8b4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default='a1b2bc11d1b742bcb8337097b4589170', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='ad05548205c446b881be00c5c646aabf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
