# Generated by Django 3.2.8 on 2021-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_author_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', to='backend.Author'),
        ),
    ]
