# Generated by Django 3.2.8 on 2021-10-15 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211015_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de650404-2de3-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de650406-2de3-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de650405-2de3-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
