# Generated by Django 3.1.6 on 2021-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210309_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_conetnt',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='backend/media/comment/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='backend/media/post/'),
        ),
    ]
