# Generated by Django 3.2.8 on 2021-10-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_author_host'),
        ('backend', '0003_alter_author_followers'),
    ]

    operations = [
    ]
