# Generated by Django 3.2.8 on 2021-10-16 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211015_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='displayName',
        ),
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(default='http://www.google.com/', editable=False, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adaad30a-2eb2-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adaad30c-2eb2-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adaad30b-2eb2-11ec-9380-525400594449'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
    ]
