# Generated by Django 3.0.2 on 2020-02-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='githubUrl',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
