# Generated by Django 3.1.6 on 2021-03-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210309_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.CharField(default='Follow', max_length=200),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='backend.follow'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='backend.like'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='backend.post'),
        ),
    ]
