# Generated by Django 3.2.8 on 2021-11-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/', max_length=500),
        ),
    ]
