# Generated by Django 3.2.8 on 2021-10-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_20211027_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/', editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('object', 'author')},
        ),
    ]
