# Generated by Django 3.1.6 on 2021-03-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210309_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
