# Generated by Django 3.2.8 on 2021-10-29 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211029_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inboxcommentlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inboxcommentlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inboxcommentlike',
            name='comment_like',
        ),
        migrations.AlterUniqueTogether(
            name='inboxpostlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inboxpostlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inboxpostlike',
            name='post_like',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=30),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='InboxCommentLike',
        ),
        migrations.DeleteModel(
            name='InboxPostLike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
