# Generated by Django 3.1.7 on 2021-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
