# Generated by Django 3.0.2 on 2020-03-06 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200221_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
