# Generated by Django 3.0.2 on 2020-03-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_post_visibleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullId',
            field=models.CharField(default='', max_length=400),
        ),
    ]
