# Generated by Django 3.1.7 on 2021-03-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210324_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='icomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icomment', to='backend.comment'),
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.CharField(default='TIM-MAINGEAR', max_length=200, primary_key=True, serialize=False),
        ),
    ]
