# Generated by Django 3.2.8 on 2021-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211016_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FOLLOWERS', 'FOLLOWERS'), ('PRIVATE', 'PRIVATE')], default=('PUBLIC', 'PUBLIC'), max_length=30),
        ),
    ]
