# Generated by Django 3.1.7 on 2021-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210328_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(default='https://github.com/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='localhost:8000', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.CharField(default='localhost:8000', max_length=200, primary_key=True, serialize=False),
        ),
    ]
