# Generated by Django 3.2.8 on 2021-11-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_author_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inbox', serialize=False, to='backend.author')),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='inbox_friend_request', to='backend.FriendRequest')),
                ('likes', models.ManyToManyField(blank=True, related_name='inbox_like', to='backend.Like')),
                ('posts', models.ManyToManyField(blank=True, related_name='inbox_post', to='backend.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inboxfriendrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inboxfriendrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inboxfriendrequest',
            name='friend_request',
        ),
        migrations.AlterUniqueTogether(
            name='inboxpost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inboxpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inboxpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='InboxComment',
        ),
        migrations.DeleteModel(
            name='InboxFriendRequest',
        ),
        migrations.DeleteModel(
            name='InboxPost',
        ),
    ]
