# Generated by Django 3.2.8 on 2021-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20211016_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
