# Generated by Django 3.2.8 on 2021-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='connect',
            field=models.BooleanField(default=True),
        ),
    ]
