# Generated by Django 3.2.8 on 2021-11-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211111_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='backend.author'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_friend_requests', to='backend.author'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'object'), name='unique_friend_request'),
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='requestor',
        ),
    ]
