# Generated by Django 3.2.8 on 2021-10-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211016_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='backend.author')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='backend.author')),
            ],
            options={
                'unique_together': {('requestor', 'requestee')},
            },
        ),
        migrations.CreateModel(
            name='InboxPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes_in_inbox', to='backend.author')),
                ('post_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.postlike')),
            ],
            options={
                'unique_together': {('author', 'post_like')},
            },
        ),
        migrations.CreateModel(
            name='InboxPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_in_inbox', to='backend.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.post')),
            ],
            options={
                'unique_together': {('author', 'post')},
            },
        ),
        migrations.CreateModel(
            name='InboxFriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_in_inbox', to='backend.author')),
                ('friend_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.friendrequest')),
            ],
            options={
                'unique_together': {('author', 'friend_request')},
            },
        ),
        migrations.CreateModel(
            name='InboxCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes_in_inbox', to='backend.author')),
                ('comment_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.commentlike')),
            ],
            options={
                'unique_together': {('author', 'comment_like')},
            },
        ),
    ]
