# Generated by Django 3.2.8 on 2021-11-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211111_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_url',
            field=models.URLField(default='<django.db.models.fields.URLField>/comments', editable=False, max_length=500),
        ),
    ]
