# Generated by Django 3.2.8 on 2021-10-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211016_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contentType',
            new_name='content_type',
        ),
    ]
