# Generated by Django 3.1.7 on 2021-04-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_auto_20210407_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='local_password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='local_username',
        ),
        migrations.AlterField(
            model_name='node',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
