# Generated by Django 3.2.8 on 2021-10-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_author_profile_image'),
        ('backend', '0013_auto_20211017_1457'),
    ]

    operations = [
    ]
