# Generated by Django 3.2.8 on 2021-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_author_host'),
        ('backend', '0013_post_comment_url'),
    ]

    operations = [
    ]
