# Generated by Django 3.1.7 on 2021-04-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210407_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://localhost:8000/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://localhost:8000/'),
        ),
    ]
