# Generated by Django 3.2.8 on 2021-10-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_friendrequest_inboxcommentlike_inboxfriendrequest_inboxpost_inboxpostlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxcommentlike',
            name='comment_like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.commentlike'),
        ),
        migrations.AlterField(
            model_name='inboxfriendrequest',
            name='friend_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.friendrequest'),
        ),
        migrations.AlterField(
            model_name='inboxpostlike',
            name='post_like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='backend.postlike'),
        ),
    ]
