# Generated by Django 3.2.8 on 2021-10-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_merge_20211022_1656'),
        ('backend', '0016_auto_20211022_2342'),
    ]

    operations = [
    ]
