# Generated by Django 3.2.8 on 2021-10-25 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_in_inbox', to='backend.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.comment')),
            ],
            options={
                'unique_together': {('author', 'comment')},
            },
        ),
    ]
