# Generated by Django 3.2.8 on 2021-11-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default='[]'),
        ),
    ]
