# Generated by Django 3.2.8 on 2021-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/', editable=False),
        ),
    ]
