# Generated by Django 3.2.8 on 2021-11-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='type',
            field=models.CharField(default='Follow', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='inbox', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', editable=False, max_length=4),
        ),
    ]
