# Generated by Django 3.2.8 on 2021-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20211121_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False),
        ),
    ]
