# Generated by Django 3.2.8 on 2021-11-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='auth_info',
        ),
        migrations.AddField(
            model_name='node',
            name='connected_auth_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='connecting_auth_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://cmput-404-social-distribution1.herokuapp.com/', editable=False),
        ),
    ]
