# Generated by Django 3.2.8 on 2021-11-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20211122_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='connected_auth_info',
        ),
        migrations.RemoveField(
            model_name='node',
            name='connecting_auth_info',
        ),
        migrations.AddField(
            model_name='node',
            name='auth_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='connecting_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
