# Generated by Django 3.2.8 on 2021-11-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20211122_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='connecting_info',
            new_name='connecting_auth_info',
        ),
    ]
