# Generated by Django 3.2.8 on 2021-11-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_rename_connecting_info_node_connecting_auth_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='connecting_auth_info',
        ),
    ]
