# Generated by Django 3.2.8 on 2021-11-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20211122_0600'),
        ('backend', '0026_remove_node_connecting_auth_info'),
    ]

    operations = [
    ]
