# Generated by Django 3.2.8 on 2021-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_merge_20211123_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False),
        ),
    ]
