# Generated by Django 3.1.6 on 2023-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.CharField(choices=[('false', 'Public'), ('true', 'Private')], default='false', max_length=20),
        ),
    ]
