# Generated by Django 4.1.5 on 2023-03-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='', max_length=500),
        ),
    ]
