# Generated by Django 3.1.6 on 2023-02-25 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230215_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='private',
        ),
        migrations.AddField(
            model_name='comments',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image/png', 'image/png;base64'), ('image/jpeg', 'image/jpeg;base64')], default='text/plain', max_length=20),
        ),
        migrations.AddField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 25, 14, 36, 36, 448040, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='refImage',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image/png', 'image/png;base64'), ('image/jpeg', 'image/jpeg;base64')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(editable=False, max_length=500),
        ),
    ]
