# Generated by Django 4.1.6 on 2023-02-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230215_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uploaded_img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image', 'image')], default='text/plain', max_length=20),
        ),
    ]
