# Generated by Django 4.1.6 on 2023-03-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
        ('posts', '0003_merge_20230310_1321'),
    ]

    operations = [
    ]
