# Generated by Django 4.1.6 on 2023-02-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_image_alter_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
