# Generated by Django 4.1.7 on 2023-03-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20230317_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
