# Generated by Django 3.1.6 on 2023-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230227_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='refImage',
            field=models.URLField(blank=True, default=''),
        ),
    ]
