# Generated by Django 4.1.7 on 2023-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
