# Generated by Django 4.1.7 on 2023-03-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_alter_author_friends'),
        ('posts', '0008_auto_20230228_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
