# Generated by Django 4.1.7 on 2023-03-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_comments_post_commentssrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
