# Generated by Django 4.1.7 on 2023-03-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_content_type_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(max_length=500),
        ),
    ]
