# Generated by Django 4.1.7 on 2023-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(editable=False, max_length=500),
        ),
    ]
