# Generated by Django 4.1.7 on 2023-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_like_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x7fa137ca4700>', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
