# Generated by Django 4.1.6 on 2023-03-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_uploaded_img_alter_image_uploaded_img'),
        ('posts', '0011_alter_like_object'),
    ]

    operations = [
    ]
