# Generated by Django 4.1.6 on 2023-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20230302_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='refImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uploaded_img',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image/png', 'image/png;base64'), ('image/jpeg', 'image/jpeg;base64')], default='text/plain', max_length=20),
        ),
    ]
