# Generated by Django 4.1.7 on 2023-03-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='categories',
        ),
    ]
