# Generated by Django 4.1.7 on 2023-03-03 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=uuid.UUID('11bd3e16-eada-4681-ac5f-0d2bab8d2bb5'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
