# Generated by Django 3.1.6 on 2021-03-03 01:41

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(default='1234', max_length=100)),
                ('displayName', models.CharField(max_length=100, unique=True)),
                ('github', models.URLField()),
                ('host', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500, null=True)),
                ('categories', models.JSONField()),
                ('count', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(max_length=20)),
                ('unlisted', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('summary', models.CharField(default='Someone Likes your post', max_length=100)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=backend.models.generate_uuid, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=50)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
            ],
        ),
    ]
