# Generated by Django 3.1.6 on 2021-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210305_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='host',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post_author_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
