# Generated by Django 3.1.6 on 2021-02-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210226_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='github_url',
            new_name='github',
        ),
    ]
