# Generated by Django 3.1.6 on 2021-02-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210226_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='e88d7c6c8ae04ce592a37cf798e654ba', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default='c7dc0838083f44868e7c76c68322f662', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default='1886f410cc5e4653ae483b3165057eb2', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default='d1447ae2241b4763b22be391a3c2e709', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
