# Generated by Django 3.1.6 on 2021-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210305_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.CharField(default='127.0.0.1:8000', max_length=50),
            preserve_default=False,
        ),
    ]
