# Generated by Django 3.1.6 on 2021-02-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210226_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='07fd3b8c5eeb460b95ff9baba07da3bc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default='bbd91826c13d41f783bcd3aab3b101b1', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default='83da8c466c4e45fb9a7792f2c204ad92', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default='60849960061a437e91c8a2e0185e2eba', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
