# Generated by Django 3.1.6 on 2021-02-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210226_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='3e2b934cf6ec43c7b3fa5027d3c39b29', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default='8cb4ced38c0540299d5ae833be954a37', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.UUIDField(default='cf29164362004f93bbf047cba6766237', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default='0126f231c55d4f4b8e167e28205830c5', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
