# Generated by Django 3.1.6 on 2021-02-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210226_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0f6300b22d684fb8b382a72c5e7202f9', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.CharField(default='2960fb6886b841a7975d6d4753c09bfd', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(default='ae7bc36a70f2442d9fde807261dc61a5', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='9db12cbe15004404a4c5bbe7e0fec860', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
