# Generated by Django 3.1.6 on 2021-02-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210226_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='e3413a3e31cd419e974b1ae0c78a5089', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='a9cd8234a94a43fc91228539903d8ba8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='c891676b2bed4fccb21645d9a65b610b', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='9f6bd93188c34caf90d452a012b4809a', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
