# Generated by Django 3.1.6 on 2021-02-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210225_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='97ba37a371394035a2638468e1b46ad8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='f70eb890727a404ba4fd7fe79805326e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='6ca953aeb88f45868241191682005df6', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='0a3d82fe1ba348ffa412d8740595ad62', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
