# Generated by Django 3.1.6 on 2021-02-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210225_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='d0fddbeb70fa4734bfe890367583cec6', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='377438933da0442799b145074becd593', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='a492647d2a1c45b49a202522c3ac0b78', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='5bd5f23739ce4969823fc0b68e7ebf32', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
