# Generated by Django 3.1.6 on 2021-02-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210227_1721'),
        ('backend', '0012_auto_20210226_1540'),
    ]

    operations = [
    ]
