# Generated by Django 3.1.6 on 2021-03-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_merge_20210227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='75a6c52cc8d1444d9ec58381b700db5d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='b331c5bf83f14e00815a11371e0a7ead', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='f3d415c766ab4a6e973217613994d498', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='f9975f851c6c45ecb926249a0794b4be', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
