# Generated by Django 3.1.6 on 2021-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210304_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='e83fe345271341b595d9ed021bf0b836', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='c880e2f8aea04321a7755362e59e4bf6', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='60962cfb6f96485b81d1dcf5c7183f73', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='6fe7207e1af5412ab9bec6afe7cdd400', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
