# Generated by Django 3.1.6 on 2021-03-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210301_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='ff6bd8b6f3f64317b3d7cd71c9e0b4f0', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='bb443fb258cb451c9a6121209243e97d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='42e7868b39624c4d9a113e9b02aead28', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
