# Generated by Django 3.1.6 on 2021-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210301_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='3cade1d8576841a7bb90999149843e84', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='e3750aae76ea469dba3afa6b66563f7f', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='f966d5a2e4a24f0babd983966ea7c3a9', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
