# Generated by Django 3.1.6 on 2021-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210301_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='1676599216ac4b6ab85e654cb4ee61af', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='1d0394730b564874b4011f1e7ed1b27e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='7853b95d3abc45f5822dccf02e39f7fb', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
