# Generated by Django 3.1.6 on 2021-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210301_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='63c7b87c00694048bbc777d7dc3b66b0', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='7e0eb8a238f1401a95af2281987111ab', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='ea8bcf6515194d3b9a78c738d33a4fe9', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
