# Generated by Django 3.1.6 on 2021-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210301_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='token',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='da2dde280fd14fa6bb798dad53a04d2c', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='d1f97357a5d2465eba84fed249d69eb7', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='b987a2d530434e09baf85e92e67548b6', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
