# Generated by Django 3.1.6 on 2021-03-01 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210301_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='2c420533911d429785d1143fbf646d3b', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='a6cca977a34446dda80dc47bd230d24f', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='173c69e559c044bea67488cc9de35eee', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
