# Generated by Django 3.1.6 on 2021-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210301_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='5701891c5fdf48e2a751854209c3bcaa', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='8616f5b9e78b43fba629a614171db11a', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='e6595d2587dd4364a972a0012479b400', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
