# Generated by Django 3.1.6 on 2021-03-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210301_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='5dad3dd3631e4d3c84bcf9d3ce165950', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='03a12a16970a4fa284916be245aad20c', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='57fa568f0b22465aa45ec71cb33634bf', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
