# Generated by Django 3.1.6 on 2021-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20210301_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='c78f006ce1014d429c40d32bfe06fc8d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='f000c8b6466d4178a30132f102abbb27', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='0527079581554f9ba64386d05a099f4a', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
