# Generated by Django 3.1.6 on 2021-03-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210302_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='05c30952fa004d17b4cdfd5dd8acb9bc', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='73835d4ca06f4a56ac634e3a870a23c4', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='2016478debc947718b667c387454c745', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
