# Generated by Django 3.1.6 on 2021-03-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20210302_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0917bc9396734c4f98d9242da515a7aa', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='85f2c72c5e9846b9a3821a5a5b3b1b2d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='2e2645cb669b457b8bbc2b68fccc8fdd', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
