# Generated by Django 3.1.6 on 2021-03-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210302_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='a5d09e201c4146a4a86e74505e09ba44', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='2d9962e157c44458bfe0126fb7709afe', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='f0bbe0e263864645ab8824af554f8611', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
