# Generated by Django 3.1.6 on 2021-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20210302_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='efd694b029ba4a9c8911669ec6ec6f9e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='9c1f2f93002b49a68723d6d333df759c', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='59386f89f90a46b7a3ada31ae4fbb6a2', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
