# Generated by Django 3.1.6 on 2021-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20210302_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='981887303ca641d39775e5078558c68f', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='1b435aba0de44b06854e931eea864360', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='e6daf83b2d85425981904bf8501cfa42', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
