# Generated by Django 3.1.6 on 2021-03-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20210302_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='4ecfbbcecbfb4c84a4d12d27dfc9a53d', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='4ccdcd78bbe34e5dbf1b4d0c74646e42', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='2d19ea0a545044d68b3207063c01e996', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
