# Generated by Django 3.1.6 on 2021-03-02 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20210302_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='token',
            field=models.CharField(default='1234', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='68d9479fce7d44b38ffd3dea2cdbffe0', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='6eaff0dc8d1c4a6d8aa1d9a13004ce23', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='fa17947a8bd4462ea98402ec127040c9', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
