# Generated by Django 4.0.2 on 2022-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'Plain Text')], max_length=350),
        ),
    ]
