# Generated by Django 4.0.2 on 2022-03-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_url',
            field=models.URLField(default='http://127.0.0.1:8000/authors/e59399f1-dad3-4717-9397-d56951821122/', max_length=250),
            preserve_default=False,
        ),
    ]
