# Generated by Django 3.2.9 on 2021-11-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.TextField(default='', verbose_name='profileImage'),
        ),
    ]
