# Generated by Django 3.2.9 on 2021-11-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.TextField(blank=True, default='', verbose_name='profileImage'),
        ),
    ]
