# Generated by Django 3.2.9 on 2021-11-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='self'),
        ),
    ]
