# Generated by Django 3.2.9 on 2021-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211125_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=80, verbose_name='host')),
                ('basic_auth', models.CharField(max_length=80, verbose_name='basic_auth')),
            ],
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follow',
        ),
    ]
