# Generated by Django 3.2.9 on 2021-11-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211125_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalhost',
            name='basic_auth',
        ),
        migrations.AddField(
            model_name='externalhost',
            name='password',
            field=models.CharField(default=123, max_length=80, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalhost',
            name='username',
            field=models.CharField(default='name', max_length=80, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isServer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='isApproved',
            field=models.BooleanField(default=False, verbose_name='isApproved'),
        ),
    ]
