# Generated by Django 3.2.9 on 2021-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211125_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalhost',
            name='token',
            field=models.CharField(blank=True, max_length=80, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='externalhost',
            name='password',
            field=models.CharField(blank=True, max_length=80, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='externalhost',
            name='username',
            field=models.CharField(blank=True, max_length=80, verbose_name='username'),
        ),
    ]
