# Generated by Django 3.2.9 on 2021-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211126_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isServer',
        ),
        migrations.AddField(
            model_name='author',
            name='isServer',
            field=models.BooleanField(default=False),
        ),
    ]
