# Generated by Django 3.2.9 on 2021-12-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211126_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=80, verbose_name='value')),
            ],
        ),
    ]
