# Generated by Django 3.2.9 on 2021-12-06 01:02

from django.db import migrations, models

def create_settings(apps, schema_editor):
    Settings = apps.get_model("core", "Settings")
    requireApproval = Settings.objects.create(key="RequireApproval",value="True")
    requireApproval.save()

    allowSignUp = Settings.objects.create(key="AllowSignUp",value="True")
    allowSignUp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settings'),
    ]

    operations = [
        migrations.RunPython(create_settings)
    ]
