# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=512)),
                ('githubUsername', models.CharField(blank=True, default=b'', max_length=39)),
                ('bio', models.TextField(blank=True, default=b'')),
                ('activated', models.BooleanField(default=False)),
                ('host', models.TextField(editable=False)),
                ('url', models.URLField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
