# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
