# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_node_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Node'),
        ),
    ]
