# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170311_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='website_url',
            new_name='host',
        ),
    ]
