# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170308_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='githubUsername',
            field=models.CharField(default=b'', max_length=39),
        ),
    ]
