# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170308_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='githubUsername',
            field=models.CharField(blank=True, default=b'', max_length=39),
        ),
    ]
