# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170308_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.CharField(max_length=512),
        ),
    ]
