# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170308_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
