# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userprofile_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
