# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170308_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='githubUsername',
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(),
        ),
    ]
