# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170308_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('website_url', models.URLField()),
                ('service_url', models.URLField()),
            ],
        ),
    ]
