# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20170310_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='host',
        ),
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
        migrations.AddField(
            model_name='author',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Node'),
        ),
    ]
