# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followed_authors',
            field=models.ManyToManyField(blank=True, related_name='_author_followed_authors_+', to='dashboard.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='dashboard.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='outgoing_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_friend_requests', to='dashboard.Author'),
        ),
    ]
