# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170311_1634'),
        ('dashboard', '0014_auto_20170311_1152'),
    ]

    operations = [
    ]
