# Generated by Django 4.1.6 on 2023-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
