# Generated by Django 3.0.3 on 2020-03-09 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted'), ('R', 'Rejected')], default='U', max_length=1)),
                ('f1Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1Ids', to=settings.AUTH_USER_MODEL)),
                ('f2Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2Ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('f1Id', 'f2Id')},
            },
        ),
    ]
