# Generated by Django 3.0.3 on 2020-03-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted'), ('R', 'Rejected')], default='U', max_length=1),
        ),
    ]
