# Generated by Django 3.0.3 on 2020-02-29 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='f1Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1Ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
