# Generated by Django 3.2 on 2023-03-10 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models.like
import service.models.post


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_auto_20230302_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('MARKDOWN', 'text/markdown'), ('text/plain', 'text/plain')], default='MARKDOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=service.models.post.get_current_date),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.URLField(primary_key=True, serialize=False)),
                ('context', models.URLField()),
                ('summary', models.CharField(max_length=50)),
                ('object', models.URLField()),
                ('published', models.DateTimeField(default=service.models.like.get_current_date, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
            ],
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(to='service.Like'),
        ),
    ]
