# Generated by Django 3.2 on 2023-03-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20230310_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, default='https://social-distribution-w23-t17.herokuapp.com'),
        ),
    ]
