# Generated by Django 3.2 on 2023-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_author_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
