# Generated by Django 3.2 on 2023-03-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20230321_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='service.author'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='service.author'),
        ),
    ]
