# Generated by Django 3.1.6 on 2021-10-12 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('passwordHash', models.TextField()),
                ('host', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inboxType', models.CharField(max_length=8)),
                ('date', models.DateTimeField()),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to='author.author')),
                ('fromAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='author.author')),
            ],
        ),
    ]
