# Generated by Django 4.1.6 on 2023-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.CharField(max_length=55),
        ),
    ]
