# Generated by Django 3.2.8 on 2021-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
