# Generated by Django 3.1.6 on 2021-10-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
        ('author', '0002_auto_20211012_1527'),
    ]

    operations = [
    ]
