# Generated by Django 3.1.6 on 2021-10-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('author', '0002_auto_20211019_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
