# Generated by Django 3.1.6 on 2021-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20211019_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='objectID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
