# Generated by Django 4.1.7 on 2023-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
