# Generated by Django 3.1.6 on 2021-10-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20211011_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='authorID',
        ),
    ]
