# Generated by Django 4.1.7 on 2023-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_inbox_options_inbox_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
