# Generated by Django 4.1.5 on 2023-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_remove_followrequest_summary_followrequest_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
