# Generated by Django 4.1.5 on 2023-03-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='Node', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='node',
            table='Node',
        ),
    ]
