# Generated by Django 4.1.5 on 2023-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_node_is_active_node_last_login_node_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='node',
            name='password',
        ),
        migrations.AlterField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
