# Generated by Django 4.1.5 on 2023-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_node_url_node_user_alter_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
