# Generated by Django 2.2.11 on 2020-03-22 21:37

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('WEB', 'Web'), ('TUTORIAL', 'Tutorial')], default='WEB', max_length=20)),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOAF', 'Friends of a friend'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private'), ('SERVERONLY', 'Server only')], default='PUBLIC', max_length=20)),
                ('unlisted', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=20)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
