# Generated by Django 2.1.5 on 2020-03-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200227_2029'),
        ('posts', '0002_auto_20200304_1934'),
    ]

    operations = [
    ]
