# Generated by Django 2.1.5 on 2020-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_20200305_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(choices=[('WEB', 'Web'), ('TUTORIAL', 'Tutorial')], default='WEB', max_length=20),
        ),
    ]
