# Generated by Django 2.1.5 on 2020-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200305_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('WEB', 'Web'), ('TUTORIAL', 'Tutorial')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
