# Generated by Django 2.1.5 on 2020-03-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200305_0648'),
        ('posts', '0007_auto_20200305_1109'),
    ]

    operations = [
    ]
