# Generated by Django 2.1.5 on 2020-03-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200305_1749'),
        ('posts', '0008_merge_20200305_1144'),
    ]

    operations = [
    ]
