# Generated by Django 4.0.2 on 2022-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_address', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
    ]
