export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_RESET = "POST_RESET";

export const POST_LIST_REQUEST = "POST_DETAIL_REQUEST";
export const POST_LIST_SUCCESS = "POST_DETAIL_SUCCESS";
export const POST_LIST_FAIL = "POST_DETAIL_FAIL";

export const WRITE_COMMENT_REQUEST = "WRITE_COMMENT_REQUEST";
export const WRITE_COMMENT_SUCCESS = "WRITE_COMMENT_SUCCESS";
export const WRITE_COMMENT_FAIL = "WRITE_COMMENT_FAIL";
