export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";

// get request for user's friend info
export const USER_FRIENDLIST_REQUEST = "USER_FRIENDLIST_REQUEST";
export const USER_FRIENDLIST_SUCCESS = "USER_FRIENDLIST_SUCCESS";
export const USER_FRIENDLIST_FAIL = "USER_FRIENDLIST_FAIL";

export const USER_DETAIL_EDIT_REQUEST = "USER_DETAIL_EDIT_REQUEST";
export const USER_DETAIL_EDIT_SUCCESS = "USER_DETAIL_EDIT_SUCCESS";
export const USER_DETAIL_EDIT_FAIL = "USER_DETAIL_EDIT_FAIL";
export const USER_DETAIL_EDIT_RESET = "USER_DETAIL_EDIT_RESET";

export const GET_USER_FOLLOWER_REQUEST = "GET_USER_FOLLOWER_REQUEST";
export const GET_USER_FOLLOWER_SUCCESS = "GET_USER_FOLLOWER_SUCCESS";
export const GET_USER_FOLLOWER_FAIL = "GET_USER_FOLLOWER_FAIL";
