# Generated by Django 4.1.2 on 2022-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='team',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (14, 14), (16, 16)], default=14),
        ),
    ]
