# Generated by Django 4.1.2 on 2022-12-04 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_rename_content_comment_comment_comment_remote_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='remote_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.remoteauthor'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
