# Generated by Django 3.1.6 on 2022-10-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_auto_20221017_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_requests_accepted', to='webserver.author')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.author')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.comment')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.like')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.post')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_requests_received', to='webserver.author')),
            ],
        ),
    ]
