# Generated by Django 4.1.2 on 2022-10-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0009_alter_author_id_alter_comment_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
