# Generated by Django 4.1.2 on 2022-10-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0010_alter_follow_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='follow_request_acceptor',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='follow_request_sender',
        ),
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbox',
            name='follow_request_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.followrequest'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='target_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL),
        ),
    ]
