# Generated by Django 4.1.2 on 2022-11-05 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0012_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_remote_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(max_length=300, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
