# Generated by Django 4.1.2 on 2022-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0013_author_is_remote_user_alter_author_username_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='auth_password',
            field=models.CharField(default='password', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='auth_username',
            field=models.CharField(default='username', max_length=300),
            preserve_default=False,
        ),
    ]
