# Generated by Django 4.1.2 on 2022-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0014_alter_author_id_alter_comment_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='auth_password',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='auth_username',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
