# Generated by Django 4.1.2 on 2022-11-14 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0015_node_auth_password_node_auth_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAuthor',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.IntegerField(choices=[(11, 11), (14, 14)], default=14),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RemotePost',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.remoteauthor')),
            ],
        ),
        migrations.AddField(
            model_name='remoteauthor',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.node'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AddField(
            model_name='follow',
            name='remote_follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.remoteauthor'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='remote_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.remoteauthor'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='remote_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webserver.remotepost'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee'), ('remote_follower', 'followee')},
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('sender', 'receiver'), ('remote_sender', 'receiver')},
        ),
    ]
