# Generated by Django 4.1.2 on 2022-11-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0016_remoteauthor_node_team_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='team',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (14, 14)], default=14),
        ),
    ]
