# Generated by Django 4.0.2 on 2022-02-15 21:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0003_alter_author_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(blank=True, max_length=350)),
                ('source', models.URLField(max_length=350)),
                ('origin', models.URLField(max_length=350)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'Utf8'), ('application/base64', 'Base64'), ('image/png;base64', 'Image Png'), ('image/jpeg;base64', 'Image Jpeg')], max_length=350)),
                ('content', models.TextField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], max_length=100)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
