# Generated by Django 4.0.2 on 2022-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_contenttype_alter_post_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
