# Generated by Django 4.0.2 on 2022-03-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
