# Generated by Django 2.1.5 on 2020-02-12 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('diplayName', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('host', models.URLField(max_length=255)),
                ('github', models.URLField(max_length=255)),
            ],
        ),
    ]
