# Generated by Django 2.1.5 on 2020-02-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='diplayName',
            new_name='displayName',
        ),
    ]
