# Generated by Django 2.1.5 on 2020-03-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200212_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_img',
            field=models.FileField(default='media/temp.jpg', upload_to='media/'),
        ),
    ]
