# Generated by Django 2.1.5 on 2020-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_author_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_img',
            field=models.FileField(default='temp.jpg', upload_to='media/'),
        ),
    ]
