# Generated by Django 2.1.5 on 2020-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200305_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_img',
            field=models.FileField(default='temp.jpg', upload_to='profile/'),
        ),
    ]
