# Generated by Django 2.1.5 on 2020-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_authorfriend_authorfriendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='changeme', max_length=50),
        ),
    ]
