# Generated by Django 2.1.5 on 2020-03-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200308_0403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='AuthorFriend',
        ),
    ]
