# Generated by Django 2.1.5 on 2020-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200310_1517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
