# Generated by Django 3.0.4 on 2020-03-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
