# Generated by Django 2.1.5 on 2020-03-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200310_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorfriend',
            unique_together={('author', 'friend')},
        ),
    ]
