# Generated by Django 4.1.6 on 2023-02-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('contentType', models.CharField(blank=True, max_length=20)),
                ('category', models.JSONField(blank=True)),
                ('comment_list', models.JSONField(blank=True, verbose_name='comment')),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('parent_post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
