# Generated by Django 4.1.6 on 2023-02-28 16:33

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_id_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='friend_list',
            field=models.JSONField(blank=True, default=apps.posts.models.Post.document_template),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.JSONField(blank=True, default=apps.posts.models.Post.document_template),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_list',
            field=models.JSONField(blank=True, default=apps.posts.models.Post.document_template, verbose_name='comment'),
        ),
    ]
