# Generated by Django 4.1.6 on 2023-03-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_profileimage'),
        ('posts', '0004_rename_followers_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
