# Generated by Django 4.1.6 on 2023-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(blank=True, choices=[('MARKDOWN', 'text/markdown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(choices=[('PUBLIC', True), ('PRIVATE', False)], default='PUBLIC'),
        ),
    ]
