# Generated by Django 4.1.6 on 2023-03-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_contenttype_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(choices=[(True, 'PUBLIC'), (False, 'PRIVATE')], default=True),
        ),
    ]
