# Generated by Django 4.1.6 on 2023-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_id_alter_comment_url_alter_friend_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(blank=True, choices=[('MARKDOWN', 'text/markdown'), ('PLAINTEXT', 'plain/Text')], max_length=20),
        ),
    ]
