# Generated by Django 4.0.2 on 2022-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_user',
            field=models.BooleanField(default=False),
        ),
    ]
