# Generated by Django 3.1.6 on 2021-10-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_user_sign_up', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
