# Generated by Django 3.1.6 on 2021-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_user_sign_up',
            field=models.BooleanField(default=True),
        ),
    ]
