# Generated by Django 3.1.6 on 2021-10-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20211019_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='allow_user_sign_up',
        ),
    ]
