# Generated by Django 3.0.3 on 2020-03-06 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='viewable_to',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='viewable_to',
            field=models.ManyToManyField(related_name='viewable_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
