# Generated by Django 3.2.8 on 2021-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
