# Generated by Django 3.1.6 on 2021-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
