# Generated by Django 3.2.8 on 2021-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='677d33bdd9f64fe4a603ce387bd7001f', editable=False, primary_key=True, serialize=False),
        ),
    ]
