# Generated by Django 3.2.8 on 2021-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='9a82fba62c1643598c8d1d94c4a56cfe', editable=False, primary_key=True, serialize=False),
        ),
    ]
