# Generated by Django 3.1.6 on 2021-10-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20211010_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='context',
            field=models.CharField(default='https://www.w3.org/ns/activitystreams', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='context',
            field=models.CharField(default='https://www.w3.org/ns/activitystreams', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post')),
            ],
            options={
                'unique_together': {('post', 'category')},
            },
        ),
    ]
