# Generated by Django 3.2.8 on 2021-10-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='82ad792ac83b4c1bab6757a2f7464c60', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='38ee5d98ede84a978f95d9b9f2980a3e', editable=False, primary_key=True, serialize=False),
        ),
    ]
