# Generated by Django 3.2.8 on 2021-10-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20211014_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='71aa28f87f454fa6b168a1308e5462fe', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='social.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='01591ce3d338449ea902d46bb52fbf2c', editable=False, primary_key=True, serialize=False),
        ),
    ]
