# Generated by Django 3.2.8 on 2021-10-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211010_1832'),
        ('social', '0004_auto_20211013_0054'),
    ]

    operations = [
    ]
