# Generated by Django 3.2.8 on 2021-10-12 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20211012_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social.author')),
                ('followers', models.ManyToManyField(related_name='who_is_following', to='social.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
