# Generated by Django 3.2.8 on 2021-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20211014_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='e42dbc71cfca4657aac5e44007f8539e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default='e0b83d6a490f46999616ce055de32610', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='8e3667af2c61412a87a2924b510bff06', editable=False, primary_key=True, serialize=False),
        ),
    ]
