# Generated by Django 3.2.8 on 2021-10-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20211012_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social.author')),
                ('followers', models.ManyToManyField(related_name='followers', to='social.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
