# Generated by Django 3.2.8 on 2021-10-14 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20211014_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default='ed12204e357640948ae2af25f504be0f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default='94a341eb1e064507b7e7e921bd651458', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='a33f9aa6142f438aae29100725ec7ae8', editable=False, primary_key=True, serialize=False),
        ),
    ]
