# Generated by Django 3.2.8 on 2021-10-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20211012_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social.author'),
        ),
    ]
