# Generated by Django 3.2 on 2023-02-28 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models.author


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(to='service.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.URLField(default=service.models.author.newId, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='_id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='_id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.author')),
                ('comments', models.ManyToManyField(to='service.Comment')),
                ('posts', models.ManyToManyField(to='service.Post')),
            ],
        ),
    ]
