# Generated by Django 3.2 on 2023-03-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20230228_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.URLField(default=None)),
                ('published', models.DateTimeField()),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_authors', to='service.author')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
            ],
        ),
        migrations.AddField(
            model_name='inbox',
            name='follow_requests',
            field=models.ManyToManyField(to='service.Follow'),
        ),
    ]
