# Generated by Django 3.0.5 on 2023-02-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.Author')),
                ('comments', models.ManyToManyField(to='service.Comment')),
                ('posts', models.ManyToManyField(to='service.Post')),
            ],
        ),
    ]
