# Generated by Django 3.2 on 2023-03-10 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_auto_20230302_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('MARKDOWN', 'text/markdown'), ('text/plain', 'text/plain')], default='MARKDOWN', max_length=64),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('context', models.URLField()),
                ('summary', models.CharField(max_length=50)),
                ('type', models.CharField(default='like', editable=False, max_length=4, null=True)),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.author')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='service.Likes')),
            ],
        ),
    ]
