# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=b''),
        ),
    ]
