# Generated by Django 4.1.7 on 2023-03-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_authormodel_host_alter_authormodel_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inboxmodel", name="comment",),
        migrations.RemoveField(model_name="inboxmodel", name="follow",),
        migrations.RemoveField(model_name="inboxmodel", name="like",),
        migrations.RemoveField(model_name="inboxmodel", name="post",),
        migrations.AddField(
            model_name="inboxmodel",
            name="object",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="inboxmodel",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.authormodel",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="inboxmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("like", "Like"),
                ],
                default="post",
                max_length=100,
            ),
        ),
    ]
