# Generated by Django 3.0.3 on 2020-02-28 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.URLField(default='http://127.0.0.1:3000/')),
                ('origin', models.URLField(default='http://127.0.0.1:3000/')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('content', models.TextField()),
                ('contentType', models.CharField(choices=[('text/plain', 'plain text'), ('text/markdown', 'markdown text'), ('image/png;base64', 'png image encoding in base64'), ('image/jpeg;base64', 'jpeg image encoding in base64'), ('application/base64', 'application ending in base64')], default='text/markdown', max_length=32)),
                ('isImage', models.BooleanField(default=False)),
                ('images', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC: visible to PUBLIC'), ('FOAF', 'FOAF: visible to friends of a friend'), ('FRIENDS', 'FRIENDS: visiable to friends'), ('PRIVATE', 'PRIVATE: visiable to users listed in visiableTo field'), ('SERVERONLY', 'SERVERONLY: visiable to a certain server')], default='PUBLIC', max_length=16)),
                ('visibleTo', models.TextField(blank=True, null=True)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('modify_post', 'Can edit or delete the posts'),),
            },
        ),
    ]
