# Generated by Django 3.0.3 on 2020-02-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC: visible to PUBLIC'), ('FOAF', 'FOAF: visible to friends of a friend'), ('FRIENDS', 'FRIENDS: visiable to friends'), ('PRIVATE', 'PRIVATE: visiable to users listed in visiableTo field'), ('SERVERONLY', 'SERVERONLY: visiable to a certain server')], default='PUBLIC', max_length=16),
        ),
    ]
