# Generated by Django 3.2.9 on 2021-11-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=280, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='origin.com', editable=False, verbose_name='origin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='source.com', editable=False, verbose_name='source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='description'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.TextField(default='http://localhost:8000', verbose_name='host'),
            preserve_default=False,
        ),
    ]
