# Generated by Django 3.2.9 on 2021-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=100000000000000, verbose_name='content'),
        ),
    ]
