# Generated by Django 3.2.9 on 2021-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211126_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='comment'),
        ),
    ]
