# Generated by Django 4.1.7 on 2023-03-23 20:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.URLField(default="", editable=False, unique=True)),
                ("type", models.CharField(default="author", max_length=100)),
                ("host", models.URLField(default="", max_length=100)),
                ("url", models.URLField(default="", max_length=100)),
                ("displayName", models.CharField(default="", max_length=100)),
                ("github", models.UUIDField(default="")),
                ("profileImage", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("created_at",),},
        ),
        migrations.CreateModel(
            name="CommentsModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.URLField(default="", editable=False, unique=True)),
                ("type", models.CharField(default="comment", max_length=100)),
                ("comment", models.TextField(default="")),
                ("host", models.URLField(default="", max_length=100)),
                ("contentType", models.CharField(default="", max_length=100)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authormodel",
                    ),
                ),
            ],
            options={"ordering": ("created_at",),},
        ),
        migrations.CreateModel(
            name="FollowModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("type", models.CharField(default="follow", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("following", models.CharField(default="", max_length=100)),
                ("follower", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("created_at",),},
        ),
        migrations.CreateModel(
            name="PostsModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.URLField(default="", editable=False, unique=True)),
                ("type", models.CharField(default="post", max_length=100)),
                ("title", models.CharField(default="", max_length=100)),
                ("source", models.URLField(default="", max_length=500)),
                (
                    "origin",
                    models.URLField(default="http://localhost:8000", max_length=500),
                ),
                ("description", models.TextField(default="")),
                ("contentType", models.CharField(default="", max_length=100)),
                ("content", models.TextField(default="")),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=100
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("FRIENDS", "Friends")],
                        default="PUBLIC",
                        max_length=100,
                    ),
                ),
                ("unlisted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authormodel",
                        to_field="id",
                    ),
                ),
            ],
            options={"ordering": ("published",),},
        ),
        migrations.CreateModel(
            name="LikeModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("summary", models.CharField(max_length=200)),
                ("type", models.CharField(default="like", max_length=100)),
                ("object", models.URLField(default="", editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authormodel",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.commentsmodel",
                        to_field="id",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postsmodel",
                        to_field="id",
                    ),
                ),
            ],
            options={"ordering": ("created_at",),},
        ),
        migrations.CreateModel(
            name="InboxModel",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("type", models.CharField(default="inbox", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authormodel",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.commentsmodel",
                        to_field="id",
                    ),
                ),
                (
                    "follow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.followmodel",
                        to_field="id",
                    ),
                ),
                (
                    "like",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.likemodel",
                        to_field="id",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postsmodel",
                        to_field="id",
                    ),
                ),
            ],
            options={"ordering": ("created_at",),},
        ),
        migrations.AddField(
            model_name="commentsmodel",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.postsmodel",
                to_field="id",
            ),
        ),
    ]
