# Generated by Django 4.1.6 on 2023-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('type', models.CharField(default='author', max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(default='', max_length=100)),
                ('displayName', models.CharField(default='', max_length=100)),
                ('profileImage', models.CharField(default='', max_length=500)),
            ],
            options={
                'ordering': ['type', 'id', 'host', 'displayName', 'profileImage'],
            },
        ),
    ]
