# Generated by Django 4.1.6 on 2023-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_authormodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='github',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='url',
            field=models.CharField(default=models.CharField(max_length=100, primary_key=True, serialize=False), max_length=100),
        ),
    ]
