# Generated by Django 4.1.6 on 2023-02-25 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_authormodel_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), blank=True, default=list, size=None),
        ),
    ]
