# Generated by Django 4.1.7 on 2023-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='origin',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
    ]
