# Generated by Django 4.1.7 on 2023-03-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
