name: Build and Test

on:
  pull_request:
    branches: [master, devel]

  workflow_dispatch:

env:
  CI: true
  NODE_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: src/app

      - name: Create build
        run: npm run build
        working-directory: src/app

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: src/app/build/

  test_app:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: src/app

      - name: Run tests
        run: npm test
        working-directory: src/app

  test_server:
    runs-on: ubuntu-latest
    needs: build
    container: node:17-alpine3.14
    services:
      postgres:
        image: postgres:14-alpine3.15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
          POSTGRES_PORT: 5432
          POSTGRES_DB: project
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: src/server/build/

      - name: Install dependencies
        run: npm ci
        working-directory: src/server

      - name: Run tests
        run: npm test
        working-directory: src/server
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: project
          JWT_SECRET: secret
